# Generated by Django 3.0.5 on 2020-06-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.TextField(max_length=30, primary_key=True, serialize=False)),
                ('symbol', models.TextField(max_length=10)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('market_cap', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_volume', models.DecimalField(decimal_places=2, max_digits=20)),
                ('high_24h', models.DecimalField(decimal_places=2, max_digits=20)),
                ('low_24h', models.DecimalField(decimal_places=2, max_digits=20)),
                ('price_change_24h', models.DecimalField(decimal_places=2, max_digits=20)),
                ('price_change_percentage_24h', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PriceTimeStamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bitcoin_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ethereum_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ripple_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('litecoin_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tether_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tezos_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('monero_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('eos_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('binancecoin_price', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
