# Generated by Django 3.0.5 on 2020-06-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceTimestamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('btc_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('eth_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('xrp_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ltc_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('usdt_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('libra_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('xmr_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('eos_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('bnb_price', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.DeleteModel(
            name='BitcoinPrice',
        ),
        migrations.DeleteModel(
            name='EthereumPrice',
        ),
    ]
