# Generated by Django 3.0.5 on 2020-06-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('market_cap', models.FloatField()),
                ('volume', models.FloatField()),
                ('circulating_supply', models.FloatField()),
                ('change_24h', models.FloatField()),
            ],
        ),
    ]
