# Generated by Django 3.0.5 on 2020-06-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='circulating_supply',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='currency',
            name='market_cap',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='currency',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='currency',
            name='volume',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
