# Generated by Django 3.0.5 on 2020-06-21 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_stock', '0002_auto_20200621_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='full_name',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='short_name',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
