# Generated by Django 3.0.5 on 2020-06-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
